module.exports.employees = [
    {
        "id": 1,
        "name": "Luke Skywalker",
        "email": "luk@test.com",
        "jobTitle":"CEO",
        "age":"40",
        "picture":"luke.jpg",
    },
    {
        "id": 2,
        "name": "anthony Helou",
        "email": "anthony@test.com",
        "jobTitle":"Senior Eningeer",
        "age":"30",
        "picture":"anthony.jpg",
    },
    {
        "id": 3,
        "name": "John Smith",
        "email": "john@test.com",
        "jobTitle":"Scrum master",
        "age":"34",
        "picture":"john.jpg",
    },
    {
        "id": 4,
        "name": "Darth Vader",
        "email": "darth@test.com",
        "jobTitle":"Engineer",
        "age":"23",
        "picture":"darth.jpg",
    },
    {
        "id": 5,
        "name": "Leia Organa",
        "email": "leia@test.com",
        "jobTitle":"marketing",
        "age":"27",
        "picture":"leia.jpg",
    },
    {
        "id": 6,
        "name": "Jon Snow",
        "email": "jonk@test.com",
        "jobTitle":"engineer",
        "age":"40",
        "picture":"jon.jpg",
    },
    {
        "id": 7,
        "name": "anthony majed",
        "email": "anthonym@test.com",
        "jobTitle":"Senior Eningeer",
        "age":"30",
        "picture":"anthonym.jpg",
    },
    {
        "id": 8,
        "name": "John Doe",
        "email": "johnd@test.com",
        "jobTitle":"Scrum master",
        "age":"34",
        "picture":"johnd.jpg",
    },
    {
        "id": 9,
        "name": "Vanessa Dagher",
        "email": "vanessa@test.com",
        "jobTitle":"marketing",
        "age":"23",
        "picture":"vanessa.jpg",
    },
    {
        "id": 10,
        "name": "Layal Awar",
        "email": "layal@test.com",
        "jobTitle":"marketing",
        "age":"27",
        "picture":"layal.jpg",
    },
    {
        "id": 11,
        "name": "Pascale Mina",
        "email": "pascale@test.com",
        "jobTitle":"BDR",
        "age":"21",
        "picture":"pascale.jpg",
    },
    {
        "id": 12,
        "name": "anthony tawil",
        "email": "anthonyt@test.com",
        "jobTitle":"Senior Eningeer",
        "age":"30",
        "picture":"anthonyt.jpg",
    },
    {
        "id": 13,
        "name": "Lionel Roob",
        "email": "lionel@test.com",
        "jobTitle":"Principal engineer",
        "age":"34",
        "picture":"lionel.jpg",
    },
    {
        "id": 14,
        "name": "Rob Stark",
        "email": "rob@test.com",
        "jobTitle":"Engineer",
        "age":"23",
        "picture":"rob.jpg",
    },
    {
        "id": 15,
        "name": "Sansa Stark",
        "email": "sansa@test.com",
        "jobTitle":"supervisor",
        "age":"27",
        "picture":"sansa.jpg",
    }
  ];